language: java
jdk:
  - oraclejdk8
before_install:
 # # install ed25519-java
 # - git clone https://github.com/sublimator/ed25519-java.git
 # - cd ed25519-java 
 # - mvn install
 # - cd ..

 - sudo apt-get install expect


 # Do this last because it takes so damn long, it's quicker to iterate on
 # refinements to prior section
 - sudo apt-get update
 - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch

 # -e shows full stack trace on errors
script: mvn -X -e install