name: Publish relese to Nexus

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare gitconfig
        run: git config --global user.email "viktor.sidochenko@gmail.com" && git config --global user.name "Viktor Sidochenko"
      - name: Test
        run: mvn clean test
      - name: Package
        run: mvn package -Dmaven.test.skip=true
      - name: Extract version from tag
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Set version
        run: mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DskipTests=true -DnewVersion=${{ steps.tag.outputs.VERSION }}
      - name: Release
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}